// <auto-generated />
using Catcher_WebAPI.Data.CanvasLogging;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Catcher_WebAPI.Data.CanvasLogging.Migrations
{
    [DbContext(typeof(GoCanvasLoggingDbContext))]
    [Migration("20201012164140_InitialGoCanvasMigration")]
    partial class InitialGoCanvasMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Catcher_WebAPI.Data.CanvasLogging.ResponseLog", b =>
                {
                    b.Property<int>("LineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("LineID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ResponseBody")
                        .IsRequired()
                        .HasColumnName("ResponseBody")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ResponseType")
                        .HasColumnName("TestRecord")
                        .HasColumnType("int");

                    b.HasKey("LineId");

                    b.ToTable("tblResponseLog");
                });
#pragma warning restore 612, 618
        }
    }
}
